name: culinary
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-doc=0.0.4=py312hca03da5_0
  - annotated-types=0.6.0=py312hca03da5_1
  - anyio=4.10.0=py312hca03da5_0
  - beautifulsoup4=4.14.3=py312hca03da5_0
  - brotlicffi=1.2.0.0=py312h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2026.01.04=py312hca03da5_0
  - cffi=2.0.0=py312h73c2a22_1
  - charset-normalizer=3.4.4=py312hca03da5_0
  - click=8.2.1=py312hca03da5_1
  - dnspython=2.8.0=py312hca03da5_0
  - email-validator=2.3.0=py312hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - fastapi=0.128.0=py312hca03da5_0
  - fastapi-cli=0.0.20=py312hca03da5_0
  - fastapi-core=0.128.0=py312hca03da5_0
  - h11=0.16.0=py312hca03da5_1
  - httpcore=1.0.9=py312hca03da5_0
  - httptools=0.7.1=py312haa24f5a_0
  - httpx=0.28.1=py312hca03da5_1
  - idna=3.11=py312hca03da5_0
  - jinja2=3.1.6=py312hca03da5_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libuv=1.48.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - markdown-it-py=4.0.0=py312hca03da5_1
  - markupsafe=3.0.2=py312h80987f9_0
  - mdurl=0.1.2=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py312hca03da5_1
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py312hca03da5_0
  - pydantic=2.12.4=py312hca03da5_0
  - pydantic-core=2.41.5=py312h931abed_1
  - pydantic-extra-types=2.11.0=py312hca03da5_0
  - pydantic-settings=2.12.0=py312hca03da5_0
  - pygments=2.19.2=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_1
  - python=3.12.12=h2bfc596_1
  - python-dotenv=1.2.1=py312hca03da5_0
  - python-multipart=0.0.22=py312hca03da5_0
  - pyyaml=6.0.3=py312h091b9d3_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py312hca03da5_1
  - rich=14.2.0=py312hca03da5_0
  - rich-toolkit=0.17.1=py312hca03da5_0
  - setuptools=80.10.2=py312hca03da5_0
  - shellingham=1.5.4=py312hca03da5_0
  - sniffio=1.3.1=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - starlette=0.47.3=py312hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - typer=0.20.0=py312hca03da5_0
  - typer-slim=0.20.0=py312hca03da5_0
  - typer-slim-standard=0.20.0=py312hca03da5_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing-inspection=0.4.2=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py312hca03da5_0
  - uvicorn=0.40.0=py312hca03da5_0
  - uvicorn-standard=0.40.0=py312hca03da5_0
  - uvloop=0.22.1=py312h8e34c70_1
  - watchfiles=1.1.1=py312h931abed_1
  - websockets=15.0.1=py312h80987f9_0
  - wheel=0.46.3=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
prefix: /Users/nfarkas/miniconda3/envs/culinary
